# Generated by Django 5.0.3 on 2024-09-11 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('situacion', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pages.proceso')),
            ],
        ),
    ]
